image: 'docker:24'

stages:
  - build-base
  - build

variables:
  DOCKER_BUILDKIT: 1

build-FastFusion-Base:
  stage: build-base
  services: [ "docker:24-dind" ]
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"
      changes:
        - Dockerfile.Base
        - requirements.txt
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
    - docker build -t hanseware/fastfusion-base:latest t hanseware/fastfusion-base:1.0.0 -f Dockerfile.Base .
    - docker push hanseware/fastfusion-base:latest
    - docker push hanseware/fastfusion-base:1.0.0

build-FastFusion:
  stage: build
  services: [ "docker:24-dind" ]
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
    - docker build -t hanseware/fastfusion:latest t hanseware/fastfusion:1.0.0 -f Dockerfile .
    - docker push hanseware/fastfusion:latest
    - docker push hanseware/fastfusion:1.0.0