image: 'docker:24'

stages:
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: LitFusion-Cache
  paths:
    - .cache/pip

build-LitFusion:
  stage: build
  services: [ "docker:24-dind" ]
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"
  script:
    - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
    - docker build -t cyb4black/litfusion:latest -f Dockerfile .
    - docker push cyb4black/litfusion:latest