image: 'docker:24'

stages:
  - build-base
  - build

variables:
  DOCKER_BUILDKIT: 1

build-LitFusion-Base:
  stage: build-base
  services: [ "docker:24-dind" ]
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"
      changes:
        - Dockerfile.Base
        - requirements.txt
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
    - docker build -t cyb4black/fastfusion-base:latest -f Dockerfile.Base .
    - docker push cyb4black/fastfusion-base:latest

build-LitFusion:
  stage: build
  services: [ "docker:24-dind" ]
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
    - docker build -t cyb4black/fastfusion:latest -f Dockerfile .
    - docker push cyb4black/fastfusion:latest