FROM python:3.11-slim
RUN apt-get update && apt-get install --no-install-recommends -y \
  build-essential python3-pip python-is-python3 python3-dev \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
# Copy LICENSE, README and requirements.txt
COPY requirements.txt /app/requirements.txt
COPY LICENSE /app/LICENSE
COPY README.md /app/README.md

RUN pip install --no-cache-dir -r requirements.txt

