# Dockerfile to determine if python versions work correctly
FROM nvcr.io/nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
        software-properties-common \
        wget \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y --no-install-recommends \
        python3.11 \
        python3.11-dev \
        python3.11-venv \
    && wget https://bootstrap.pypa.io/get-pip.py -O get-pip.py \
    && python3.11 get-pip.py \
    && rm get-pip.py \
    && ln -sf /usr/bin/python3.11 /usr/bin/python \
    && ln -sf /usr/local/bin/pip3.11 /usr/local/bin/pip \
    && python --version \
    && pip --version \
    && apt-get purge -y --auto-remove software-properties-common \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN python --version
RUN pip --version
RUN python3 --version
RUN pip3 --version
RUN python3.11 --version
RUN pip3.11 --version